# Generated by Django 3.0.7 on 2020-06-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher_name', models.CharField(max_length=150, verbose_name='Диспетчерское наименование')),
                ('switching_resource', models.FloatField(verbose_name='Остаточный коммутационный ресурс, %')),
                ('mechanical_resource', models.FloatField(verbose_name='Остаточный механический ресурс, %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Выключатель',
                'verbose_name_plural': 'Выключатели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NameOfBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование Филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoltageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_class', models.IntegerField(verbose_name='Класс напряжения Выключателя, кВ')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Наименование класса напряжения Выключателя, кВ')),
            ],
            options={
                'verbose_name': 'Напряжение',
                'verbose_name_plural': 'Напряжения',
                'ordering': ['voltage_class'],
            },
        ),
        migrations.CreateModel(
            name='SwitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_type', models.CharField(max_length=150, verbose_name='Тип выключателя')),
                ('rated_breaking_current', models.FloatField(verbose_name='Номинальный ток отключения, кА')),
                ('rated_current', models.FloatField(verbose_name='Номинальный ток, А')),
                ('first_bound', models.FloatField(verbose_name='Нижняя граница первого интервала, %')),
                ('second_bound', models.FloatField(verbose_name='Нижняя граница второго интервала, %')),
                ('third_bound', models.FloatField(verbose_name='Нижняя граница третьего интервала, %')),
                ('first_bound_number_of_commutation', models.FloatField(verbose_name='Количество комутаций первого интервала, кА')),
                ('second_bound_number_of_commutation', models.FloatField(verbose_name='Количество комутаций второго интервала, кА')),
                ('third_bound_number_of_commutation', models.FloatField(verbose_name='Количество комутаций третьего интервала, кА')),
                ('mechanical_resource', models.IntegerField(verbose_name='Механический ресурс')),
                ('voltage_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.VoltageClass', verbose_name='Класс напряжения Выключателя,кВ')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['switch_type'],
            },
        ),
        migrations.CreateModel(
            name='NameOfSubstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование ПС')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.NameOfBranch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Подстанция',
                'verbose_name_plural': 'Подстанции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommutationJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_commutation', models.DateTimeField(verbose_name='Дата коммутации')),
                ('current_of_commutation', models.FloatField(verbose_name='Ток комутации, А')),
                ('user_name', models.CharField(max_length=150, verbose_name='Кто внес запись')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.NameOfBranch', verbose_name='Филиал')),
                ('dispatcher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.CircuitBreakers', verbose_name='Диспетчерское наименование')),
                ('name_of_substation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.NameOfSubstation', verbose_name='Наименование ПС')),
            ],
            options={
                'verbose_name': 'Комутация',
                'verbose_name_plural': 'Комутации',
                'ordering': ['-date_of_commutation'],
            },
        ),
        migrations.AddField(
            model_name='circuitbreakers',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.NameOfBranch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='circuitbreakers',
            name='name_of_substation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.NameOfSubstation', verbose_name='Наименование ПС'),
        ),
        migrations.AddField(
            model_name='circuitbreakers',
            name='switch_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.SwitchType', verbose_name='Тип выключателя'),
        ),
    ]
